name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Authenticate to Google Cloud using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud CLI and set up the project
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build & push Docker image to Google Container Registry (GCR)
      - name: Build & push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/mevanl-site || echo "Build completed with non-fatal errors"

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mevanl-site \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/mevanl-site \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
